import { defaultSettings, type StampSettings } from "./settings"

export interface StampPreset {
  id: string
  label: string
  /** One line on what the preset is imitating */
  note: string
  patch: Partial<StampSettings>
}

/*
 * Each preset is a complete look, applied over the defaults so the result is
 * the same however the sliders were left. Artwork is never touched: a preset
 * re-plates the picture you already loaded.
 */
export const presets: StampPreset[] = [
  {
    id: "high-value",
    label: "High value",
    note: "1922 series: arched vignette, curved country line, value tablets",
    patch: {
      format: "portrait",
      edge: "perforated",
      gauge: 11,
      print: "engraved",
      inkColor: "#14418c",
      frameColor: "#14418c",
      vignetteColor: "#14418c",
      typeface: "grotesque",
      frame: "arched",
      vignette: "arch",
      vignetteRule: true,
      ornament: "scroll",
      ornamentSize: 0.1,
      countryArc: true,
      tablets: true,
      ribbon: true,
      country: "United States Postage",
      denomination: "2",
      caption: "U.S. Capitol",
      artFit: "cover",
      margin: 0.055,
      relief: 0.55,
      toning: 0.26,
    },
  },
  {
    id: "commemorative",
    label: "Commemorative",
    note: "1980s issue: ruled picture box, didone date line, heavy numeral",
    patch: {
      format: "portrait",
      edge: "perforated",
      gauge: 11.5,
      print: "offset",
      inkColor: "#1d3f6e",
      frameColor: "#1b1b1b",
      vignetteColor: "#1b1b1b",
      typeface: "didone",
      frame: "none",
      vignette: "rect",
      vignetteRule: true,
      countryArc: false,
      tablets: false,
      country: "",
      denomination: "25",
      caption: "New York",
      artFit: "cover",
      margin: 0.06,
      toning: 0.14,
      relief: 0.18,
    },
  },
  {
    id: "penny",
    label: "Penny black",
    note: "1840: imperforate, typeset, deeply aged",
    patch: {
      format: "portrait",
      edge: "imperforate",
      tear: 0.45,
      print: "typeset",
      inkColor: "#22201f",
      frameColor: "#22201f",
      typeface: "serif",
      frame: "ornate",
      vignette: "none",
      country: "Postage",
      denomination: "One Penny",
      caption: "",
      artFit: "cover",
      margin: 0.05,
      toning: 0.62,
      foxing: 0.35,
      wear: 0.5,
      relief: 0.7,
      ink: 1.15,
    },
  },
  {
    id: "airmail",
    label: "Air mail",
    note: "Wide format, oval vignette, two plates",
    patch: {
      format: "wide",
      edge: "perforated",
      gauge: 12,
      print: "engraved",
      inkColor: "#1b4f9c",
      frameColor: "#a41326",
      vignetteColor: "#a41326",
      typeface: "didone",
      frame: "rule",
      vignette: "oval",
      vignetteRule: true,
      feather: 0.2,
      ornament: "leaf",
      ornamentSize: 0.09,
      country: "Air Mail",
      denomination: "$1.20",
      caption: "",
      artFit: "cover",
      margin: 0.05,
      toning: 0.12,
    },
  },
  {
    id: "definitive",
    label: "Definitive",
    note: "Small workhorse: one colour, tight margins, gothic caps",
    patch: {
      format: "tall",
      edge: "perforated",
      gauge: 13.5,
      holeSize: 0.28,
      print: "photogravure",
      inkColor: "#1f5c3a",
      frameColor: "#1f5c3a",
      typeface: "condensed",
      frame: "rule",
      vignette: "none",
      country: "Postage",
      denomination: "8c",
      caption: "",
      artFit: "cover",
      margin: 0.045,
      toning: 0.18,
      size: 0.62,
    },
  },
  {
    id: "self-adhesive",
    label: "Self-adhesive",
    note: "Modern die-cut wave, full-bleed photograph, no frame",
    patch: {
      format: "landscape",
      edge: "wavy",
      gauge: 10,
      holeSize: 0.34,
      tear: 0.1,
      print: "offset",
      typeface: "grotesque",
      frame: "none",
      vignette: "none",
      designOn: true,
      country: "USA",
      denomination: "Forever",
      caption: "",
      frameColor: "#ffffff",
      artFit: "cover",
      artBleed: true,
      margin: 0.05,
      toning: 0.04,
      foxing: 0,
      wear: 0.05,
      fiber: 0.28,
      relief: 0.1,
    },
  },
  {
    id: "circular",
    label: "Round vignette",
    note: "Portrait medallion in a circle, ornamented corners",
    patch: {
      format: "square",
      edge: "perforated",
      gauge: 12.5,
      print: "engraved",
      inkColor: "#5a3a86",
      frameColor: "#5a3a86",
      vignetteColor: "#5a3a86",
      typeface: "grotesque",
      frame: "classic",
      vignette: "circle",
      vignetteRule: true,
      feather: 0.12,
      ornament: "rosette",
      ornamentSize: 0.12,
      countryArc: true,
      country: "Republic",
      denomination: "5",
      tablets: true,
      artFit: "cover",
      margin: 0.05,
      toning: 0.24,
    },
  },
  {
    id: "cancelled",
    label: "Used copy",
    note: "Off cover: struck, toned, and handled",
    patch: {
      format: "portrait",
      edge: "perforated",
      gauge: 11,
      tear: 0.5,
      print: "engraved",
      inkColor: "#8a1c2b",
      frameColor: "#8a1c2b",
      typeface: "serif",
      frame: "classic",
      vignette: "none",
      country: "United States Postage",
      denomination: "13¢",
      artFit: "cover",
      margin: 0.07,
      toning: 0.44,
      foxing: 0.3,
      wear: 0.45,
      postmarkOn: true,
      postmarkStyle: "both",
      postmarkStrength: 0.62,
    },
  },
]

/** A preset is a whole look, so it replaces the sheet rather than layering. */
export function applyPreset(p: StampPreset): StampSettings {
  return { ...defaultSettings, ...p.patch }
}
